### ISSUE TITLE
I cant install npp.connections successfully!

### ISSUE THREAD

**Issue by boubou** [vladk1973/npp.connections#3]
Hi Vlad, ;)
If I try to install the npp.connections with PM, PM download the plugin and it asks to restart NotePad++ to install the plugin.
When NotePad++ restart, there is no errors BUT if I go to PM again, npp.connections is not installed.
How can I install the plugin successfully ?
I am using the latest NotePad++ version (7.5.5) and the latest PM version (1.4.10.0).
Thanks you very much for your plugin and your help!
Sincerely!

**Comment by vladk1973** [comment]
Hi!
This was due to an incorrect commit in the plugins_template.xml, placed [here](https://github.com/bruderstein/npp-plugins-x64/blob/master/plugins/plugins_template.xml)
The plugins_template, which is downloaded to the local computer by plugin manager, contains the wrong path to the plugin. I corrected the archived release npp.connections-1.0.1-x64.zip, now the installation will be done correctly.
Thank you for your interest!
